// This file has been generated by Py++.

#include "boost/python.hpp"

#include "indexing_suite/value_traits.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "indexing_suite/set.hpp"

#include "cell_headers.hpp"

namespace bp = boost::python;

struct CaBasedCellPopulation_less__3__greater__wrapper : CaBasedCellPopulation< 3 >, bp::wrapper< CaBasedCellPopulation< 3 > > {

    CaBasedCellPopulation_less__3__greater__wrapper(::PottsMesh< 3 > & rMesh, ::std::vector< boost::shared_ptr<Cell> > & rCells, ::std::vector< unsigned int > const locationIndices, unsigned int latticeCarryingCapacity=1U, bool deleteMesh=false, bool validate=false )
    : CaBasedCellPopulation<3>( boost::ref(rMesh), boost::ref(rCells), locationIndices, latticeCarryingCapacity, deleteMesh, validate )
      , bp::wrapper< CaBasedCellPopulation< 3 > >(){
        // constructor
    
    }

    CaBasedCellPopulation_less__3__greater__wrapper(::PottsMesh< 3 > & rMesh )
    : CaBasedCellPopulation<3>( boost::ref(rMesh) )
      , bp::wrapper< CaBasedCellPopulation< 3 > >(){
        // constructor
    
    }

    virtual void AcceptCellWriter( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > > pCellWriter, ::CellPtr pCell ) {
        if( bp::override func_AcceptCellWriter = this->get_override( "AcceptCellWriter" ) )
            func_AcceptCellWriter( pCellWriter, pCell );
        else{
            this->CaBasedCellPopulation< 3 >::AcceptCellWriter( pCellWriter, pCell );
        }
    }
    
    void default_AcceptCellWriter( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > > pCellWriter, ::CellPtr pCell ) {
        CaBasedCellPopulation< 3 >::AcceptCellWriter( pCellWriter, pCell );
    }

    virtual void AcceptPopulationCountWriter( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > pPopulationCountWriter ) {
        if( bp::override func_AcceptPopulationCountWriter = this->get_override( "AcceptPopulationCountWriter" ) )
            func_AcceptPopulationCountWriter( pPopulationCountWriter );
        else{
            this->CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter( pPopulationCountWriter );
        }
    }
    
    void default_AcceptPopulationCountWriter( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > pPopulationCountWriter ) {
        CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter( pPopulationCountWriter );
    }

    virtual void AcceptPopulationWriter( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > pPopulationWriter ) {
        if( bp::override func_AcceptPopulationWriter = this->get_override( "AcceptPopulationWriter" ) )
            func_AcceptPopulationWriter( pPopulationWriter );
        else{
            this->CaBasedCellPopulation< 3 >::AcceptPopulationWriter( pPopulationWriter );
        }
    }
    
    void default_AcceptPopulationWriter( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > pPopulationWriter ) {
        CaBasedCellPopulation< 3 >::AcceptPopulationWriter( pPopulationWriter );
    }

    virtual ::CellPtr AddCell( ::CellPtr pNewCell, ::boost::numeric::ublas::c_vector< double, 3 > const & rCellDivisionVector, ::CellPtr pParentCell=::CellPtr( ) ) {
        if( bp::override func_AddCell = this->get_override( "AddCell" ) )
            return func_AddCell( pNewCell, boost::ref(rCellDivisionVector), pParentCell );
        else{
            return this->CaBasedCellPopulation< 3 >::AddCell( pNewCell, boost::ref(rCellDivisionVector), pParentCell );
        }
    }
    
    ::CellPtr default_AddCell( ::CellPtr pNewCell, ::boost::numeric::ublas::c_vector< double, 3 > const & rCellDivisionVector, ::CellPtr pParentCell=::CellPtr( ) ) {
        return CaBasedCellPopulation< 3 >::AddCell( pNewCell, boost::ref(rCellDivisionVector), pParentCell );
    }

    virtual void AddCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        if( bp::override func_AddCellUsingLocationIndex = this->get_override( "AddCellUsingLocationIndex" ) )
            func_AddCellUsingLocationIndex( index, pCell );
        else{
            this->CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex( index, pCell );
        }
    }
    
    void default_AddCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex( index, pCell );
    }

    virtual double EvaluateDivisionPropensity( unsigned int currentNodeIndex, unsigned int targetNodeIndex, ::CellPtr pCell ) {
        if( bp::override func_EvaluateDivisionPropensity = this->get_override( "EvaluateDivisionPropensity" ) )
            return func_EvaluateDivisionPropensity( currentNodeIndex, targetNodeIndex, pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity( currentNodeIndex, targetNodeIndex, pCell );
        }
    }
    
    double default_EvaluateDivisionPropensity( unsigned int currentNodeIndex, unsigned int targetNodeIndex, ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity( currentNodeIndex, targetNodeIndex, pCell );
    }

    virtual ::boost::numeric::ublas::c_vector< double, 3 > GetLocationOfCellCentre( ::CellPtr pCell ) {
        if( bp::override func_GetLocationOfCellCentre = this->get_override( "GetLocationOfCellCentre" ) )
            return func_GetLocationOfCellCentre( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::GetLocationOfCellCentre( pCell );
        }
    }
    
    ::boost::numeric::ublas::c_vector< double, 3 > default_GetLocationOfCellCentre( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::GetLocationOfCellCentre( pCell );
    }

    virtual ::std::set< unsigned int > GetNeighbouringLocationIndices( ::CellPtr pCell ) {
        if( bp::override func_GetNeighbouringLocationIndices = this->get_override( "GetNeighbouringLocationIndices" ) )
            return func_GetNeighbouringLocationIndices( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices( pCell );
        }
    }
    
    ::std::set< unsigned int > default_GetNeighbouringLocationIndices( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices( pCell );
    }

    virtual unsigned int GetNumNodes(  ) {
        if( bp::override func_GetNumNodes = this->get_override( "GetNumNodes" ) )
            return func_GetNumNodes(  );
        else{
            return this->CaBasedCellPopulation< 3 >::GetNumNodes(  );
        }
    }
    
    unsigned int default_GetNumNodes(  ) {
        return CaBasedCellPopulation< 3 >::GetNumNodes( );
    }

    virtual double GetVolumeOfCell( ::CellPtr pCell ) {
        if( bp::override func_GetVolumeOfCell = this->get_override( "GetVolumeOfCell" ) )
            return func_GetVolumeOfCell( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::GetVolumeOfCell( pCell );
        }
    }
    
    double default_GetVolumeOfCell( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::GetVolumeOfCell( pCell );
    }

    virtual double GetWidth( unsigned int const & rDimension ) {
        if( bp::override func_GetWidth = this->get_override( "GetWidth" ) )
            return func_GetWidth( rDimension );
        else{
            return this->CaBasedCellPopulation< 3 >::GetWidth( rDimension );
        }
    }
    
    double default_GetWidth( unsigned int const & rDimension ) {
        return CaBasedCellPopulation< 3 >::GetWidth( rDimension );
    }

    virtual bool IsCellAssociatedWithADeletedLocation( ::CellPtr pCell ) {
        if( bp::override func_IsCellAssociatedWithADeletedLocation = this->get_override( "IsCellAssociatedWithADeletedLocation" ) )
            return func_IsCellAssociatedWithADeletedLocation( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation( pCell );
        }
    }
    
    bool default_IsCellAssociatedWithADeletedLocation( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation( pCell );
    }

    virtual bool IsRoomToDivide( ::CellPtr pCell ) {
        if( bp::override func_IsRoomToDivide = this->get_override( "IsRoomToDivide" ) )
            return func_IsRoomToDivide( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::IsRoomToDivide( pCell );
        }
    }
    
    bool default_IsRoomToDivide( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::IsRoomToDivide( pCell );
    }

    virtual bool IsSiteAvailable( unsigned int index, ::CellPtr pCell ) {
        if( bp::override func_IsSiteAvailable = this->get_override( "IsSiteAvailable" ) )
            return func_IsSiteAvailable( index, pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::IsSiteAvailable( index, pCell );
        }
    }
    
    bool default_IsSiteAvailable( unsigned int index, ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::IsSiteAvailable( index, pCell );
    }

    virtual void OpenWritersFiles( ::OutputFileHandler & rOutputFileHandler ) {
        if( bp::override func_OpenWritersFiles = this->get_override( "OpenWritersFiles" ) )
            func_OpenWritersFiles( boost::ref(rOutputFileHandler) );
        else{
            this->CaBasedCellPopulation< 3 >::OpenWritersFiles( boost::ref(rOutputFileHandler) );
        }
    }
    
    void default_OpenWritersFiles( ::OutputFileHandler & rOutputFileHandler ) {
        CaBasedCellPopulation< 3 >::OpenWritersFiles( boost::ref(rOutputFileHandler) );
    }

    virtual void OutputCellPopulationParameters( ::out_stream & rParamsFile ) {
        if( bp::override func_OutputCellPopulationParameters = this->get_override( "OutputCellPopulationParameters" ) )
            func_OutputCellPopulationParameters( boost::ref(rParamsFile) );
        else{
            this->CaBasedCellPopulation< 3 >::OutputCellPopulationParameters( boost::ref(rParamsFile) );
        }
    }
    
    void default_OutputCellPopulationParameters( ::out_stream & rParamsFile ) {
        CaBasedCellPopulation< 3 >::OutputCellPopulationParameters( boost::ref(rParamsFile) );
    }

    virtual void RemoveCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        if( bp::override func_RemoveCellUsingLocationIndex = this->get_override( "RemoveCellUsingLocationIndex" ) )
            func_RemoveCellUsingLocationIndex( index, pCell );
        else{
            this->CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex( index, pCell );
        }
    }
    
    void default_RemoveCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex( index, pCell );
    }

    virtual unsigned int RemoveDeadCells(  ) {
        if( bp::override func_RemoveDeadCells = this->get_override( "RemoveDeadCells" ) )
            return func_RemoveDeadCells(  );
        else{
            return this->CaBasedCellPopulation< 3 >::RemoveDeadCells(  );
        }
    }
    
    unsigned int default_RemoveDeadCells(  ) {
        return CaBasedCellPopulation< 3 >::RemoveDeadCells( );
    }

    virtual void Update( bool hasHadBirthsOrDeaths=true ) {
        if( bp::override func_Update = this->get_override( "Update" ) )
            func_Update( hasHadBirthsOrDeaths );
        else{
            this->CaBasedCellPopulation< 3 >::Update( hasHadBirthsOrDeaths );
        }
    }
    
    void default_Update( bool hasHadBirthsOrDeaths=true ) {
        CaBasedCellPopulation< 3 >::Update( hasHadBirthsOrDeaths );
    }

    virtual void UpdateCellLocations( double dt ) {
        if( bp::override func_UpdateCellLocations = this->get_override( "UpdateCellLocations" ) )
            func_UpdateCellLocations( dt );
        else{
            this->CaBasedCellPopulation< 3 >::UpdateCellLocations( dt );
        }
    }
    
    void default_UpdateCellLocations( double dt ) {
        CaBasedCellPopulation< 3 >::UpdateCellLocations( dt );
    }

};

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< boost::numeric::ublas::c_vector< double, 3 > >{

    static bool const equality_comparable = false;
    

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< boost::shared_ptr< AbstractCaSwitchingUpdateRule< 3 > > >{

    static bool const equality_comparable = false;
    

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< boost::shared_ptr< AbstractCaUpdateRule< 3 > > >{

    static bool const equality_comparable = false;
    

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< boost::shared_ptr< Cell > >{

    static bool const equality_comparable = false;
    

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

namespace boost { namespace python { namespace indexing {

template<>
struct value_traits< boost::shared_ptr< SimpleCell< 3 > > >{

    static bool const equality_comparable = false;
    

    static bool const less_than_comparable = false;
    

    template<typename PythonClass, typename Policy>
    static void visit_container_class(PythonClass &, Policy const &){
        
    }

};

}/*indexing*/ } /*python*/ } /*boost*/

BOOST_PYTHON_MODULE(_chaste_project_Angiogenesis_cell){
    { //::std::vector< unsigned int >
        typedef bp::class_< std::vector< unsigned int > > vector_less__unsigned_int__greater__exposer_t;
        vector_less__unsigned_int__greater__exposer_t vector_less__unsigned_int__greater__exposer = vector_less__unsigned_int__greater__exposer_t( "vector_less__unsigned_int__greater_" );
        bp::scope vector_less__unsigned_int__greater__scope( vector_less__unsigned_int__greater__exposer );
        vector_less__unsigned_int__greater__exposer.def( bp::indexing::vector_suite< std::vector< unsigned int > >() );
    }

    { //::std::vector< boost::shared_ptr<SimpleCell<3> > >
        typedef bp::class_< std::vector< boost::shared_ptr<SimpleCell<3> > > > __type_exposer_t;
        __type_exposer_t __type_exposer = __type_exposer_t( "__type" );
        bp::scope __type_scope( __type_exposer );
        __type_exposer.def( bp::indexing::vector_suite< std::vector< boost::shared_ptr<SimpleCell<3> > > >() );
    }

    { //::std::vector< boost::shared_ptr<Cell> >
        typedef bp::class_< std::vector< boost::shared_ptr<Cell> > > __type_exposer_t;
        __type_exposer_t __type_exposer = __type_exposer_t( "__type" );
        bp::scope __type_scope( __type_exposer );
        __type_exposer.def( bp::indexing::vector_suite< std::vector< boost::shared_ptr<Cell> > >() );
    }

    { //::std::vector< boost::shared_ptr<AbstractCaUpdateRule<3> > >
        typedef bp::class_< std::vector< boost::shared_ptr<AbstractCaUpdateRule<3> > > > __type_exposer_t;
        __type_exposer_t __type_exposer = __type_exposer_t( "__type" );
        bp::scope __type_scope( __type_exposer );
        __type_exposer.def( bp::indexing::vector_suite< std::vector< boost::shared_ptr<AbstractCaUpdateRule<3> > > >() );
    }

    { //::std::vector< boost::shared_ptr<AbstractCaSwitchingUpdateRule<3> > >
        typedef bp::class_< std::vector< boost::shared_ptr<AbstractCaSwitchingUpdateRule<3> > > > __type_exposer_t;
        __type_exposer_t __type_exposer = __type_exposer_t( "__type" );
        bp::scope __type_scope( __type_exposer );
        __type_exposer.def( bp::indexing::vector_suite< std::vector< boost::shared_ptr<AbstractCaSwitchingUpdateRule<3> > > >() );
    }

    bp::class_< std::vector< boost::numeric::ublas::c_vector<double, 3> > >("vector_less__boost_scope_numeric_scope_ublas_scope_c_vector_less_double_comma__3_greater___greater_")    
        .def( bp::indexing::vector_suite< std::vector< boost::numeric::ublas::c_vector<double, 3> > >() );

    { //::std::set< unsigned int >
        typedef bp::class_< std::set< unsigned int > > set_less__unsigned_int__greater__exposer_t;
        set_less__unsigned_int__greater__exposer_t set_less__unsigned_int__greater__exposer = set_less__unsigned_int__greater__exposer_t( "set_less__unsigned_int__greater_" );
        bp::scope set_less__unsigned_int__greater__scope( set_less__unsigned_int__greater__exposer );
        set_less__unsigned_int__greater__exposer.def( bp::indexing::set_suite< std::set< unsigned int > >() );
    }

    { //::CaBasedCellPopulation< 3 >
        typedef bp::class_< CaBasedCellPopulation_less__3__greater__wrapper, boost::noncopyable > CaBasedCellPopulation3_exposer_t;
        CaBasedCellPopulation3_exposer_t CaBasedCellPopulation3_exposer = CaBasedCellPopulation3_exposer_t( "CaBasedCellPopulation3", bp::init< PottsMesh< 3 > &, std::vector< boost::shared_ptr<Cell> > &, std::vector< unsigned int >, bp::optional< unsigned int, bool, bool > >(( bp::arg("rMesh"), bp::arg("rCells"), bp::arg("locationIndices"), bp::arg("latticeCarryingCapacity")=(unsigned int)(1U), bp::arg("deleteMesh")=(bool)(false), bp::arg("validate")=(bool)(false) )) );
        bp::scope CaBasedCellPopulation3_scope( CaBasedCellPopulation3_exposer );
        CaBasedCellPopulation3_exposer.def( bp::init< PottsMesh< 3 > & >(( bp::arg("rMesh") )) );
        bp::implicitly_convertible< PottsMesh< 3 > &, CaBasedCellPopulation< 3 > >();
        { //::CaBasedCellPopulation< 3 >::AcceptCellWriter
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AcceptCellWriter_function_type)( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > >,::CellPtr ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AcceptCellWriter_function_type)( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > >,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptCellWriter"
                , AcceptCellWriter_function_type(&::CaBasedCellPopulation< 3 >::AcceptCellWriter)
                , default_AcceptCellWriter_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptCellWriter)
                , ( bp::arg("pCellWriter"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AcceptPopulationCountWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AcceptPopulationCountWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptPopulationCountWriter"
                , AcceptPopulationCountWriter_function_type(&::CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter)
                , default_AcceptPopulationCountWriter_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptPopulationCountWriter)
                , ( bp::arg("pPopulationCountWriter") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AcceptPopulationWriter
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AcceptPopulationWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AcceptPopulationWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptPopulationWriter"
                , AcceptPopulationWriter_function_type(&::CaBasedCellPopulation< 3 >::AcceptPopulationWriter)
                , default_AcceptPopulationWriter_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptPopulationWriter)
                , ( bp::arg("pPopulationWriter") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddCell
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::CellPtr ( exported_class_t::*AddCell_function_type)( ::CellPtr,::boost::numeric::ublas::c_vector< double, 3 > const &,::CellPtr ) ;
            typedef ::CellPtr ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AddCell_function_type)( ::CellPtr,::boost::numeric::ublas::c_vector< double, 3 > const &,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddCell"
                , AddCell_function_type(&::CaBasedCellPopulation< 3 >::AddCell)
                , default_AddCell_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AddCell)
                , ( bp::arg("pNewCell"), bp::arg("rCellDivisionVector"), bp::arg("pParentCell")=::CellPtr( ) ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AddCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddCellUsingLocationIndex"
                , AddCellUsingLocationIndex_function_type(&::CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex)
                , default_AddCellUsingLocationIndex_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AddCellUsingLocationIndex)
                , ( bp::arg("index"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddSwitchingUpdateRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddSwitchingUpdateRule_function_type)( ::boost::shared_ptr< AbstractCaSwitchingUpdateRule< 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddSwitchingUpdateRule"
                , AddSwitchingUpdateRule_function_type( &::CaBasedCellPopulation< 3 >::AddSwitchingUpdateRule )
                , ( bp::arg("pUpdateRule") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddUpdateRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddUpdateRule_function_type)( ::boost::shared_ptr< AbstractCaUpdateRule< 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddUpdateRule"
                , AddUpdateRule_function_type( &::CaBasedCellPopulation< 3 >::AddUpdateRule )
                , ( bp::arg("pUpdateRule") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*EvaluateDivisionPropensity_function_type)( unsigned int,unsigned int,::CellPtr ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_EvaluateDivisionPropensity_function_type)( unsigned int,unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "EvaluateDivisionPropensity"
                , EvaluateDivisionPropensity_function_type(&::CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity)
                , default_EvaluateDivisionPropensity_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_EvaluateDivisionPropensity)
                , ( bp::arg("currentNodeIndex"), bp::arg("targetNodeIndex"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetCaBasedDivisionRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::boost::shared_ptr< AbstractCaBasedDivisionRule< 3 > > ( exported_class_t::*GetCaBasedDivisionRule_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetCaBasedDivisionRule"
                , GetCaBasedDivisionRule_function_type( &::CaBasedCellPopulation< 3 >::GetCaBasedDivisionRule ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetLocationOfCellCentre
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::boost::numeric::ublas::c_vector< double, 3 > ( exported_class_t::*GetLocationOfCellCentre_function_type)( ::CellPtr ) ;
            typedef ::boost::numeric::ublas::c_vector< double, 3 > ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetLocationOfCellCentre_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetLocationOfCellCentre"
                , GetLocationOfCellCentre_function_type(&::CaBasedCellPopulation< 3 >::GetLocationOfCellCentre)
                , default_GetLocationOfCellCentre_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetLocationOfCellCentre)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::std::set< unsigned int > ( exported_class_t::*GetNeighbouringLocationIndices_function_type)( ::CellPtr ) ;
            typedef ::std::set< unsigned int > ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetNeighbouringLocationIndices_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNeighbouringLocationIndices"
                , GetNeighbouringLocationIndices_function_type(&::CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices)
                , default_GetNeighbouringLocationIndices_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetNeighbouringLocationIndices)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetNumNodes
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef unsigned int ( exported_class_t::*GetNumNodes_function_type)(  ) ;
            typedef unsigned int ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetNumNodes_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNumNodes"
                , GetNumNodes_function_type(&::CaBasedCellPopulation< 3 >::GetNumNodes)
                , default_GetNumNodes_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetNumNodes) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetVolumeOfCell
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*GetVolumeOfCell_function_type)( ::CellPtr ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetVolumeOfCell_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetVolumeOfCell"
                , GetVolumeOfCell_function_type(&::CaBasedCellPopulation< 3 >::GetVolumeOfCell)
                , default_GetVolumeOfCell_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetVolumeOfCell)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetWidth
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*GetWidth_function_type)( unsigned int const & ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetWidth_function_type)( unsigned int const & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetWidth"
                , GetWidth_function_type(&::CaBasedCellPopulation< 3 >::GetWidth)
                , default_GetWidth_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetWidth)
                , ( bp::arg("rDimension") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsCellAssociatedWithADeletedLocation_function_type)( ::CellPtr ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsCellAssociatedWithADeletedLocation_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsCellAssociatedWithADeletedLocation"
                , IsCellAssociatedWithADeletedLocation_function_type(&::CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation)
                , default_IsCellAssociatedWithADeletedLocation_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsCellAssociatedWithADeletedLocation)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsRoomToDivide
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsRoomToDivide_function_type)( ::CellPtr ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsRoomToDivide_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsRoomToDivide"
                , IsRoomToDivide_function_type(&::CaBasedCellPopulation< 3 >::IsRoomToDivide)
                , default_IsRoomToDivide_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsRoomToDivide)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsSiteAvailable
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsSiteAvailable_function_type)( unsigned int,::CellPtr ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsSiteAvailable_function_type)( unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsSiteAvailable"
                , IsSiteAvailable_function_type(&::CaBasedCellPopulation< 3 >::IsSiteAvailable)
                , default_IsSiteAvailable_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsSiteAvailable)
                , ( bp::arg("index"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::OpenWritersFiles
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*OpenWritersFiles_function_type)( ::OutputFileHandler & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_OpenWritersFiles_function_type)( ::OutputFileHandler & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "OpenWritersFiles"
                , OpenWritersFiles_function_type(&::CaBasedCellPopulation< 3 >::OpenWritersFiles)
                , default_OpenWritersFiles_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_OpenWritersFiles)
                , ( bp::arg("rOutputFileHandler") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::OutputCellPopulationParameters
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*OutputCellPopulationParameters_function_type)( ::out_stream & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_OutputCellPopulationParameters_function_type)( ::out_stream & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "OutputCellPopulationParameters"
                , OutputCellPopulationParameters_function_type(&::CaBasedCellPopulation< 3 >::OutputCellPopulationParameters)
                , default_OutputCellPopulationParameters_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_OutputCellPopulationParameters)
                , ( bp::arg("rParamsFile") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveAllSwitchingUpdateRules
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*RemoveAllSwitchingUpdateRules_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveAllSwitchingUpdateRules"
                , RemoveAllSwitchingUpdateRules_function_type( &::CaBasedCellPopulation< 3 >::RemoveAllSwitchingUpdateRules ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveAllUpdateRules
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*RemoveAllUpdateRules_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveAllUpdateRules"
                , RemoveAllUpdateRules_function_type( &::CaBasedCellPopulation< 3 >::RemoveAllUpdateRules ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*RemoveCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_RemoveCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveCellUsingLocationIndex"
                , RemoveCellUsingLocationIndex_function_type(&::CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex)
                , default_RemoveCellUsingLocationIndex_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_RemoveCellUsingLocationIndex)
                , ( bp::arg("index"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveDeadCells
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef unsigned int ( exported_class_t::*RemoveDeadCells_function_type)(  ) ;
            typedef unsigned int ( CaBasedCellPopulation_less__3__greater__wrapper::*default_RemoveDeadCells_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveDeadCells"
                , RemoveDeadCells_function_type(&::CaBasedCellPopulation< 3 >::RemoveDeadCells)
                , default_RemoveDeadCells_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_RemoveDeadCells) );
        
        }
        { //::CaBasedCellPopulation< 3 >::SetCaBasedDivisionRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetCaBasedDivisionRule_function_type)( ::boost::shared_ptr< AbstractCaBasedDivisionRule< 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "SetCaBasedDivisionRule"
                , SetCaBasedDivisionRule_function_type( &::CaBasedCellPopulation< 3 >::SetCaBasedDivisionRule )
                , ( bp::arg("pCaBasedDivisionRule") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::Update
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*Update_function_type)( bool ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_Update_function_type)( bool ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "Update"
                , Update_function_type(&::CaBasedCellPopulation< 3 >::Update)
                , default_Update_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_Update)
                , ( bp::arg("hasHadBirthsOrDeaths")=(bool)(true) ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::UpdateCellLocations
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*UpdateCellLocations_function_type)( double ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_UpdateCellLocations_function_type)( double ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "UpdateCellLocations"
                , UpdateCellLocations_function_type(&::CaBasedCellPopulation< 3 >::UpdateCellLocations)
                , default_UpdateCellLocations_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_UpdateCellLocations)
                , ( bp::arg("dt") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::rGetSwitchingUpdateRuleCollection
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::std::vector< boost::shared_ptr<AbstractCaSwitchingUpdateRule<3> > > const & ( exported_class_t::*rGetSwitchingUpdateRuleCollection_function_type)(  ) const;
            
            CaBasedCellPopulation3_exposer.def( 
                "rGetSwitchingUpdateRuleCollection"
                , rGetSwitchingUpdateRuleCollection_function_type( &::CaBasedCellPopulation< 3 >::rGetSwitchingUpdateRuleCollection )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        { //::CaBasedCellPopulation< 3 >::rGetUpdateRuleCollection
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::std::vector< boost::shared_ptr<AbstractCaUpdateRule<3> > > const & ( exported_class_t::*rGetUpdateRuleCollection_function_type)(  ) const;
            
            CaBasedCellPopulation3_exposer.def( 
                "rGetUpdateRuleCollection"
                , rGetUpdateRuleCollection_function_type( &::CaBasedCellPopulation< 3 >::rGetUpdateRuleCollection )
                , bp::return_value_policy< bp::copy_const_reference >() );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< CaBasedCellPopulation<3> > >();
        bp::implicitly_convertible< boost::shared_ptr< CaBasedCellPopulation< 3 > >, boost::shared_ptr< AbstractOnLatticeCellPopulation< 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< CaBasedCellPopulation< 3 > >, boost::shared_ptr< AbstractCellPopulation< 3, 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< CaBasedCellPopulation< 3 > >, boost::shared_ptr< Identifiable > >();
    }

    bp::class_< CancerCellMutationState >( "CancerCellMutationState", bp::init< >() );

    { //::SimpleCell< 3 >
        typedef bp::class_< SimpleCell< 3 > > SimpleCell3_exposer_t;
        SimpleCell3_exposer_t SimpleCell3_exposer = SimpleCell3_exposer_t( "SimpleCell3", bp::init< bp::optional< double, double, double > >(( bp::arg("v1")=0, bp::arg("v2")=0, bp::arg("v3")=0 )) );
        bp::scope SimpleCell3_scope( SimpleCell3_exposer );
        bp::implicitly_convertible< double, SimpleCell< 3 > >();
        SimpleCell3_exposer.def( bp::init< boost::numeric::ublas::c_vector< double, 3 > >(( bp::arg("location") )) );
        bp::implicitly_convertible< boost::numeric::ublas::c_vector< double, 3 >, SimpleCell< 3 > >();
        { //::SimpleCell< 3 >::Create
        
            typedef SimpleCell< 3 > exported_class_t;
            typedef ::boost::shared_ptr< SimpleCell< 3 > > ( *Create_function_type )( double,double,double );
            
            SimpleCell3_exposer.def( 
                "Create"
                , Create_function_type( &::SimpleCell< 3 >::Create )
                , ( bp::arg("v1")=0, bp::arg("v2")=0, bp::arg("v3")=0 ) );
        
        }
        { //::SimpleCell< 3 >::Create
        
            typedef SimpleCell< 3 > exported_class_t;
            typedef ::boost::shared_ptr< SimpleCell< 3 > > ( *Create_function_type )( ::boost::numeric::ublas::c_vector< double, 3 > );
            
            SimpleCell3_exposer.def( 
                "Create"
                , Create_function_type( &::SimpleCell< 3 >::Create )
                , ( bp::arg("location") ) );
        
        }
        { //::SimpleCell< 3 >::GetIndex
        
            typedef SimpleCell< 3 > exported_class_t;
            typedef unsigned int ( exported_class_t::*GetIndex_function_type)(  ) ;
            
            SimpleCell3_exposer.def( 
                "GetIndex"
                , GetIndex_function_type( &::SimpleCell< 3 >::GetIndex ) );
        
        }
        { //::SimpleCell< 3 >::GetReferenceLengthScale
        
            typedef SimpleCell< 3 > exported_class_t;
            typedef ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ( exported_class_t::*GetReferenceLengthScale_function_type)(  ) const;
            
            SimpleCell3_exposer.def( 
                "GetReferenceLengthScale"
                , GetReferenceLengthScale_function_type( &::SimpleCell< 3 >::GetReferenceLengthScale ) );
        
        }
        { //::SimpleCell< 3 >::SetIndex
        
            typedef SimpleCell< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetIndex_function_type)( unsigned int ) ;
            
            SimpleCell3_exposer.def( 
                "SetIndex"
                , SetIndex_function_type( &::SimpleCell< 3 >::SetIndex )
                , ( bp::arg("index") ) );
        
        }
        { //::SimpleCell< 3 >::SetReferenceLengthScale
        
            typedef SimpleCell< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetReferenceLengthScale_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            SimpleCell3_exposer.def( 
                "SetReferenceLengthScale"
                , SetReferenceLengthScale_function_type( &::SimpleCell< 3 >::SetReferenceLengthScale )
                , ( bp::arg("lenthScale") ) );
        
        }
        SimpleCell3_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< SimpleCell<3> > >();
        bp::implicitly_convertible< boost::shared_ptr< SimpleCell< 3 > >, boost::shared_ptr< ChastePoint< 3 > > >();
    }

    { //::SimpleCellPopulation< 3 >
        typedef bp::class_< SimpleCellPopulation< 3 > > SimpleCellPopulation3_exposer_t;
        SimpleCellPopulation3_exposer_t SimpleCellPopulation3_exposer = SimpleCellPopulation3_exposer_t( "SimpleCellPopulation3", bp::init< >() );
        bp::scope SimpleCellPopulation3_scope( SimpleCellPopulation3_exposer );
        { //::SimpleCellPopulation< 3 >::AddCell
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddCell_function_type)( ::boost::shared_ptr< SimpleCell< 3 > > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "AddCell"
                , AddCell_function_type( &::SimpleCellPopulation< 3 >::AddCell )
                , ( bp::arg("pCell") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::AddCells
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddCells_function_type)( ::std::vector< boost::shared_ptr<SimpleCell<3> > > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "AddCells"
                , AddCells_function_type( &::SimpleCellPopulation< 3 >::AddCells )
                , ( bp::arg("cells") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::BooleanWithVesselNetwork
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*BooleanWithVesselNetwork_function_type)( ::boost::shared_ptr< VesselNetwork< 3 > > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "BooleanWithVesselNetwork"
                , BooleanWithVesselNetwork_function_type( &::SimpleCellPopulation< 3 >::BooleanWithVesselNetwork )
                , ( bp::arg("pNetwork") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::Create
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef ::boost::shared_ptr< SimpleCellPopulation< 3 > > ( *Create_function_type )(  );
            
            SimpleCellPopulation3_exposer.def( 
                "Create"
                , Create_function_type( &::SimpleCellPopulation< 3 >::Create ) );
        
        }
        { //::SimpleCellPopulation< 3 >::GenerateCellsAtPoints
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*GenerateCellsAtPoints_function_type)( ::std::vector< boost::numeric::ublas::c_vector<double, 3> > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "GenerateCellsAtPoints"
                , GenerateCellsAtPoints_function_type( &::SimpleCellPopulation< 3 >::GenerateCellsAtPoints )
                , ( bp::arg("points") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::GenerateCellsOnGrid
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*GenerateCellsOnGrid_function_type)( unsigned int,unsigned int,unsigned int,::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double >,::boost::numeric::ublas::c_vector< double, 3 > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "GenerateCellsOnGrid"
                , GenerateCellsOnGrid_function_type( &::SimpleCellPopulation< 3 >::GenerateCellsOnGrid )
                , ( bp::arg("xDim"), bp::arg("yDim"), bp::arg("zDim"), bp::arg("spacing"), bp::arg("origin") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::GenerateCellsOnGrid
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*GenerateCellsOnGrid_function_type)( ::boost::shared_ptr< Part< 3 > >,::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "GenerateCellsOnGrid"
                , GenerateCellsOnGrid_function_type( &::SimpleCellPopulation< 3 >::GenerateCellsOnGrid )
                , ( bp::arg("pPart"), bp::arg("spacing") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::GetCells
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef ::std::vector< boost::shared_ptr<SimpleCell<3> > > ( exported_class_t::*GetCells_function_type)(  ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "GetCells"
                , GetCells_function_type( &::SimpleCellPopulation< 3 >::GetCells ) );
        
        }
        { //::SimpleCellPopulation< 3 >::GetVtk
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef ::vtkSmartPointer< vtkPoints > ( exported_class_t::*GetVtk_function_type)(  ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "GetVtk"
                , GetVtk_function_type( &::SimpleCellPopulation< 3 >::GetVtk ) );
        
        }
        { //::SimpleCellPopulation< 3 >::SetReferenceLengthScale
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetReferenceLengthScale_function_type)( ::boost::units::quantity< boost::units::unit< boost::units::list< boost::units::dim< boost::units::length_base_dimension, boost::units::static_rational< 1, 1 > >, boost::units::dimensionless_type >, boost::units::homogeneous_system< boost::units::list< boost::units::si::meter_base_unit, boost::units::list< boost::units::scaled_base_unit< boost::units::cgs::gram_base_unit, boost::units::scale< 10, boost::units::static_rational< 3 > > >, boost::units::list< boost::units::si::second_base_unit, boost::units::list< boost::units::si::ampere_base_unit, boost::units::list< boost::units::si::kelvin_base_unit, boost::units::list< boost::units::si::mole_base_unit, boost::units::list< boost::units::si::candela_base_unit, boost::units::list< boost::units::angle::radian_base_unit, boost::units::list< boost::units::angle::steradian_base_unit, boost::units::dimensionless_type > > > > > > > > > >, void >, double > ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "SetReferenceLengthScale"
                , SetReferenceLengthScale_function_type( &::SimpleCellPopulation< 3 >::SetReferenceLengthScale )
                , ( bp::arg("lenthScale") ) );
        
        }
        { //::SimpleCellPopulation< 3 >::Write
        
            typedef SimpleCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*Write_function_type)( ::std::string const & ) ;
            
            SimpleCellPopulation3_exposer.def( 
                "Write"
                , Write_function_type( &::SimpleCellPopulation< 3 >::Write )
                , ( bp::arg("rFileName") ) );
        
        }
        SimpleCellPopulation3_exposer.staticmethod( "Create" );
        bp::register_ptr_to_python< boost::shared_ptr< SimpleCellPopulation<3> > >();
    }

    { //::GenerateCaBasedCellPopulation
    
        typedef ::boost::shared_ptr< CaBasedCellPopulation< 3 > > ( *GenerateCaBasedCellPopulation_function_type )( ::boost::shared_ptr< PottsMesh< 3 > >,::std::vector< boost::shared_ptr<Cell> >,::std::vector< unsigned int > );
        
        bp::def( 
            "GenerateCaBasedCellPopulation"
            , GenerateCaBasedCellPopulation_function_type( &::GenerateCaBasedCellPopulation )
            , ( bp::arg("pMesh"), bp::arg("cells"), bp::arg("location_indices") ) );
    
    }

    { //::GenerateCell
    
        typedef ::boost::shared_ptr< Cell > ( *GenerateCell_function_type )( ::std::string const &,::std::string const & );
        
        bp::def( 
            "GenerateCell"
            , GenerateCell_function_type( &::GenerateCell )
            , ( bp::arg("mutation_state"), bp::arg("cell_cycle_model") ) );
    
    }
}
