set(ProjectAngiogenesis_INCLUDE_DIRS "")
set(ProjectAngiogenesis_LIBRARIES "")
set(PREFIX ${CMAKE_CURRENT_LIST_DIR})

list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/geometry/)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/geometry/generators)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/mesh/)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/mesh/utilities)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/mesh/external)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/mesh/external/tetgen1.5.0)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/pde/boundary_conditions)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/pde/discrete_sources)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/pde/problem)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/pde/solvers)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/ode)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/vessel)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/vessel/properties)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/vessel/generators)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/cell)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/cell/properties/mutations)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/cell/writers)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/cell/killers)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/cell/cycle)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/population/combined)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/flow)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/flow/calculators)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/flow/calculators/alarcon03)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/flow/haematocrit)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/flow/structural_adaptation)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/angiogenesis)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/angiogenesis/migration_rules)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/angiogenesis/migration_rules/lattice)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/angiogenesis/migration_rules/off_lattice)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/angiogenesis/regression)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/angiogenesis/sprouting_rules)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/simulation/wrappers)
list(APPEND ProjectAngiogenesis_INCLUDE_DIRS ${PREFIX}/src/wrapper)
