package:
  name: chaste
  version: 3.4

source:
  path: /scratch/jgrogan/Software/chaste

build:
  number: 3

requirements:
  build:
    - python
    - openmpi ==1.8.8
    - xsd
    - xerces-c
    - vtk ==5.10.1
    - petsc ==3.6.3
    - boost ==1.59

  run:
    - python
    - openmpi ==1.8.8
    - xsd
    - xerces-c
    - vtk ==5.10.1
    - petsc ==3.6.3
    - boost ==1.59
    - scipy
    - matplotlib
    - petsc4py ==3.6.0
    - pandas
    - jupyter

about:
  home: http://www.cs.ox.ac.uk/chaste/
  license: 3-clause BSD

