package:
  name: openmpi
  version: 1.8.8

source:
  fn: openmpi-1.8.8.tar.bz2
  url: http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.8.tar.bz2

about:
  home: http://www.open-mpi.org/
  license: new BSD  (http://www.open-mpi.org/community/license.php)
